name: geopandas-dev
channels:
    - conda-forge
dependencies:
    - python
    # required
    - fiona>=1.8.19
    - pandas>=1.1.0
    - pygeos
    - pyproj>=3.0.1
    - shapely>=1.7.1
    - packaging

    # testing
    - pytest>=3.1.0
    - pytest-cov
    - pytest-xdist
    - fsspec
    - codecov
    # styling
    - black
    - pre-commit

    # optional
    - folium
    - xyzservices
    - scipy
    - libspatialite
    - geoalchemy2
    - pyarrow
    # doctest testing
    - pytest-doctestplus
    # geocoding
    - geopy
    # geodatabase access
    - psycopg2>=2.8.0
    - SQLAlchemy>2
    # plotting
    - matplotlib>=3.2
    - mapclassify
    # spatial access methods
    - rtree>=0.9
